# Generated by Django 3.1.5 on 2021-04-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('exp_date', models.DateField()),
                ('price', models.FloatField(blank=True, default='0', null=True)),
                ('quantity', models.IntegerField()),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('sell_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('purchase_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('Last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('near_exp_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('exp_date', models.DateField()),
                ('price', models.FloatField(blank=True, default='0', null=True)),
                ('quantity', models.IntegerField()),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('sell_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('purchase_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('Last_updated', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('Sales_date', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
