# Generated by Django 3.1.5 on 2021-04-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
