# Generated by Django 3.1.5 on 2021-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinehistory',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
