# Generated by Django 3.1.5 on 2021-04-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_medicine_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinehistory',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
