# Generated by Django 3.1.5 on 2021-03-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_medicine_near_exp_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('exp_date', models.DateField()),
                ('price', models.FloatField(blank=True, default='0', null=True)),
                ('quantity', models.IntegerField()),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('sell_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('purchase_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('Last_updated', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
