# Generated by Django 3.1.5 on 2021-03-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_medicinehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='near_exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
