# Generated by Django 3.1.5 on 2021-03-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210326_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Sales_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
